"""add accommodation pricing

Revision ID: 11d1d6bf2700
Revises: 0bb7f0b89e77
Create Date: 2026-09-02 18:38:05.426268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11d1d6bf2700'
down_revision: Union[str, Sequence[str], None] = '0bb7f0b89e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodation_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departure_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('price_per_person', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('occupied_beds', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['departure_id'], ['tour_departures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('departure_id', 'code', name='uq_accommodation_rate_departure_code')
    )
    op.create_index(op.f('ix_accommodation_rates_departure_id'), 'accommodation_rates', ['departure_id'], unique=False)
    op.add_column('bookings', sa.Column('calculated_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('bookings', sa.Column('manual_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('bookings', sa.Column('price_comment', sa.Text(), nullable=True))
    op.add_column('participants', sa.Column('accommodation_rate_id', sa.Integer(), nullable=True))
    op.add_column('participants', sa.Column('accommodation_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('participants', sa.Column('occupied_beds', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_participants_accommodation_rate_id'), 'participants', ['accommodation_rate_id'], unique=False)
    op.create_foreign_key(None, 'participants', 'accommodation_rates', ['accommodation_rate_id'], ['id'])
    op.create_unique_constraint('uq_room_departure_number', 'rooms', ['departure_id', 'number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_room_departure_number', 'rooms', type_='unique')
    op.drop_constraint(None, 'participants', type_='foreignkey')
    op.drop_index(op.f('ix_participants_accommodation_rate_id'), table_name='participants')
    op.drop_column('participants', 'occupied_beds')
    op.drop_column('participants', 'accommodation_price')
    op.drop_column('participants', 'accommodation_rate_id')
    op.drop_column('bookings', 'price_comment')
    op.drop_column('bookings', 'manual_price')
    op.drop_column('bookings', 'calculated_price')
    op.drop_index(op.f('ix_accommodation_rates_departure_id'), table_name='accommodation_rates')
    op.drop_table('accommodation_rates')
    # ### end Alembic commands ###
